// Auth actions.
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";

// Card actions.
export const CREATE_CARD_SUCCESS = "CREATE_CARD_SUCCESS";
export const DELETE_CARD_OPTIMISTIC = "DELETE_CARD_OPTIMISTIC";
export const LOAD_CARDS_SUCCESS = "LOAD_CARDS_SUCCESS";
export const UPDATE_CARD_SUCCESS = "UPDATE_CARD_SUCCESS";

// User actions.
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const DELETE_USER_OPTIMISTIC = "DELETE_USER_OPTIMISTIC";
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

// API actions.
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
