export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const DELETE_USER_OPTIMISTIC = "DELETE_USER_OPTIMISTIC";
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
